### PR TITLE
Update external-dependency.md

### PR DESCRIPTION
**Pull request by maurya-anuj**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind test
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by omung-g** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/omung-g/kubeedge/pull/32#issuecomment-500777350" title="Approved">srivatsav123</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=omung-g%2Fkubeedge).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/omung-g/kubeedge/blob/master/OWNERS)~~ [srivatsav123]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by omung-g** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/omung-g/kubeedge/pull/32#issuecomment-500778204" title="Approved">pavan187</a>*, *<a href="https://github.com/omung-g/kubeedge/pull/32#issuecomment-500777350" title="Approved">srivatsav123</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=omung-g%2Fkubeedge).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/omung-g/kubeedge/blob/master/OWNERS)~~ [pavan187,srivatsav123]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by omung-g — APPROVED** [review]

**Comment by omung-g** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/omung-g/kubeedge/pull/32#issuecomment-500779605" title="Approved">pavan187</a>*, *<a href="https://github.com/omung-g/kubeedge/pull/32#issuecomment-500777350" title="Approved">srivatsav123</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=omung-g%2Fkubeedge).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/omung-g/kubeedge/blob/master/OWNERS)~~ [pavan187,srivatsav123]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by pavan187 — APPROVED** [review]

**Comment by omung-g** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/omung-g/kubeedge/pull/32#pullrequestreview-248081756" title="Approved">pavan187</a>*, *<a href="https://github.com/omung-g/kubeedge/pull/32#issuecomment-500777350" title="Approved">srivatsav123</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=omung-g%2Fkubeedge).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/omung-g/kubeedge/blob/master/OWNERS)~~ [pavan187,srivatsav123]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
